### ISSUE TITLE
Crashes with Forge 1.7.10

### ISSUE THREAD

**Issue by mizar1** [daveyliam/mapwriter#27]
Tried to different versions of Forge 1.7.10, crashed with both 1180 and 1208

java.lang.NoSuchMethodError: net.minecraft.client.gui.ScaledResolution.<init>(Lnet/minecraft/client/settings/GameSettings;II)V
    at mapwriter.map.mapmode.MapMode.setScreenRes(MapMode.java:101)
    at mapwriter.map.MapRenderer.draw(MapRenderer.java:260)
    at mapwriter.map.MiniMap.drawCurrentMap(MiniMap.java:96)
    at mapwriter.Mw.onTick(Mw.java:619)
    at mapwriter.forge.MwForge.renderMap(MwForge.java:67)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_5_MwForge_renderMap_Post.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899)
    at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:176)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at mapwriter.map.mapmode.MapMode.setScreenRes(MapMode.java:101)
    at mapwriter.map.MapRenderer.draw(MapRenderer.java:260)
    at mapwriter.map.MiniMap.drawCurrentMap(MiniMap.java:96)
    at mapwriter.Mw.onTick(Mw.java:619)
    at mapwriter.forge.MwForge.renderMap(MwForge.java:67)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_5_MwForge_renderMap_Post.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899)
    at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:176)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['mizar1'/13020, l='MpServer', x=35.53, y=108.62, z=-617.23]]
    Chunk stats: MultiplayerChunkCache: 120, 120
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (184,60,-616), Chunk: (at 8,3,8 in 11,-39; contains blocks 176,0,-624 to 191,255,-609), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
    Level time: 159685072 game time, 160492535 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 1 total; [EntityClientPlayerMP['mizar1'/13020, l='MpServer', x=35.53, y=108.62, z=-617.23]]
    Retry entities: 0 total; []
    Server brand: Spigot
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.9.4
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 116839728 bytes (111 MB) / 299925504 bytes (286 MB) up to 2138767360 bytes (2039 MB)
    JVM Flags: 1 total; -Xmx2G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.25.1208 Minecraft Forge 10.13.0.1208 4 mods loaded, 4 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.25.1208} [Forge Mod Loader](forge-1.7.10-10.13.0.1208.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.0.1208} [Minecraft Forge](forge-1.7.10-10.13.0.1208.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MapWriter{2.1.1} [MapWriter](MapWriter-1.7.2-2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Launched Version: 1.7.10-Forge10.13.0.1208
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 6970M OpenGL Engine GL version 2.1 ATI-1.24.35, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by elix-x** [comment]
Are you serious??? 1.7.10 is still not avaible! An i'm getting the same crash!
