### ISSUE TITLE
Getting log spam.

### ISSUE THREAD

**Issue by MuresanSergiu** [daveyliam/mapwriter#33]
Basically I'm getting this message (every tick?):
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.IndexOutOfBoundsException
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.io.RandomAccessFile.readBytes(Native Method)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.io.RandomAccessFile.read(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at javax.imageio.stream.FileImageInputStream.read(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at com.sun.imageio.plugins.common.SubImageInputStream.read(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at com.sun.imageio.plugins.common.InputStreamAdapter.read(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.io.SequenceInputStream.read(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.util.zip.InflaterInputStream.fill(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.util.zip.InflaterInputStream.read(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.io.BufferedInputStream.fill(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.io.BufferedInputStream.read(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.io.FilterInputStream.read(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at com.sun.imageio.plugins.png.PNGImageReader.decodePass(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at com.sun.imageio.plugins.png.PNGImageReader.decodeImage(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at com.sun.imageio.plugins.png.PNGImageReader.readImage(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at com.sun.imageio.plugins.png.PNGImageReader.read(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at javax.imageio.ImageIO.read(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at javax.imageio.ImageIO.read(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mapwriter.region.SurfacePixels.loadImage(SurfacePixels.java:141)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mapwriter.region.SurfacePixels.load(SurfacePixels.java:46)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mapwriter.region.SurfacePixels.getPixels(SurfacePixels.java:65)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mapwriter.region.SurfacePixels.getOrAllocatePixels(SurfacePixels.java:71)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mapwriter.region.SurfacePixels.updateScaled(SurfacePixels.java:115)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mapwriter.region.Region.updateNextZoomLevel(Region.java:143)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mapwriter.region.Region.updateZoomLevels(Region.java:155)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mapwriter.region.SurfacePixels.updateChunk(SurfacePixels.java:91)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mapwriter.region.Region.updateChunk(Region.java:166)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mapwriter.region.RegionManager.updateChunk(RegionManager.java:123)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mapwriter.tasks.UpdateSurfaceChunksTask.run(UpdateSurfaceChunksTask.java:24)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.util.concurrent.FutureTask.run(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:22:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.Thread.run(Unknown Source)

This is not really an issue but at times my log gets too big (1GB+) and minecraft shuts down.
I'm using the MapWriter mod integrated in Opis at the moment.

**Comment by QORTEC** [comment]
I have the same issue with the integrated version of MapWriter in Opis.

Console Spam (Clean):
https://gist.github.com/QORTEC/2387bca0202c98572cde
